# Importing Libraries

In [144]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.model_selection import LeavePOut
from  sklearn.model_selection import ShuffleSplit 
from sklearn.model_selection import cross_val_score

from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier


from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score
from sklearn.model_selection import train_test_split
from sklearn import metrics, model_selection

In [145]:
df = pd.read_csv('gender-prediction.csv')
df

height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]

# Splitting and Encoding Input and Ouput Variables

In [146]:
x = df.drop('gender', axis=1)
y = df['gender']

In [147]:
labels = preprocessing.LabelEncoder()
beard_encoded = labels.fit_transform(x.beard)
hair_encoded = labels.fit_transform(x.hair_length)
scarf_encoded = labels.fit_transform(x.scarf)
eye_encoded = labels.fit_transform(x.eye_color)
gender_encoded = labels.fit_transform(y)


In [148]:
features = list(zip(x.height,x.weight,beard_encoded,hair_encoded,x.shoe_size,scarf_encoded,eye_encoded))
target = gender_encoded

# Training Using Standard Split

In [149]:
X_train, x_test, Y_train, y_test = train_test_split(features, target, test_size = 0.33, random_state = 2)

# Random Forest Classifier

In [150]:
model = RandomForestClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  100.0
[[10  0]
 [ 0 17]]


# Support Vector Machine Classifier

In [151]:
model = SVC()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  77.77777777777779
[[ 7  3]
 [ 3 14]]


# MultiLayer Perceptron

In [152]:
model = MLPClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  62.96296296296296
[[ 0 10]
 [ 0 17]]


# Now Using 80/20 Split on Data

In [153]:
X_train, x_test, Y_train, y_test = train_test_split(features, target, test_size = 0.20, random_state = 2)

# Random Forest Classifier

In [154]:
model = RandomForestClassifier()
model.fit(X_train,Y_train)# Random Forest Classifier
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  100.0
[[ 6  0]
 [ 0 10]]


# Support Vector Machine Classifier

In [155]:
model = SVC()# Support Vector Machine Classifier
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  81.25
[[4 2]
 [1 9]]


# MultiLayer Perceptron

In [156]:
model = MLPClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  100.0
[[ 6  0]
 [ 0 10]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Now Excluding Scarf And Beard Attribute

In [157]:
featuresnew = list(zip(x.height,x.weight,hair_encoded,x.shoe_size,eye_encoded))


In [158]:
X_train, x_test, Y_train, y_test = train_test_split(featuresnew, target, test_size = 0.20, random_state = 2)

# Random Forest Classifier

In [159]:
# Random Forest Classifiermodel = RandomForestClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  100.0
[[ 6  0]
 [ 0 10]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Support Vector Machine Classifier

In [160]:
model = SVC()
model.fit(X_train,Y_train)# Support Vector Machine Classifier
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  81.25
[[4 2]
 [1 9]]


# MultiLayer Perceptron

In [161]:
# MultiLayer Perceptronmodel = MLPClassifier()
model.fit(X_train,Y_train)
prediction = model.predict(x_test)
model_acc = accuracy_score(y_test, prediction)*100
print("ACCURACY = ",model_acc)
model_cm = metrics.confusion_matrix(y_test, prediction)
print(model_cm)

ACCURACY =  81.25
[[4 2]
 [1 9]]


# Decision Tree

In [162]:
model = DecisionTreeClassifier()

# Leave POut Cross Validation

In [163]:
lpo=LeavePOut(p=2)
mean_score = cross_val_score(model, features, target, scoring="f1", cv = lpo).mean()
print(mean_score*100)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1580: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
C:\ProgramData\Anaconda3\lib\site-packages\skl

77.72151898734178


# Monte Carlo Cross Validation

In [164]:
mc=ShuffleSplit(n_splits=5,test_size=0.33,random_state=2)
mean_score = cross_val_score(model, features, target, scoring="f1", cv = mc).mean()
print(mean_score*100)

94.91367833748257


# Fetching DataSet with New Instances

In [165]:
dfnew = pd.read_csv('updated.csv')
dfnew.tail()

height  weight beard hair_length  shoe_size scarf eye_color  gender
80      65     169    no        long         41    no      blue  female
81      72     172   yes       short         43    no     brown    male
82      69     168    no      medium         42   yes     brown  female
83      82     179    no       short         45    no     black    male
84      77     175   yes      medium         44    no     brown    male

In [166]:
X = dfnew.drop('gender', axis=1)
Y = dfnew['gender']
beard_encoded = labels.fit_transform(X.beard)
hair_encoded = labels.fit_transform(X.hair_length)
scarf_encoded = labels.fit_transform(X.scarf)
eye_encoded = labels.fit_transform(X.eye_color)
gender_encoded = labels.fit_transform(Y)


In [167]:
feature = list(zip(X.height,X.weight,beard_encoded,hair_encoded,X.shoe_size,scarf_encoded,eye_encoded))
targets = gender_encoded

# Using Naive Bayes Model To Predict New Instances

In [168]:
model = GaussianNB()
model.fit(feature,targets)
prediction = model.predict([[65, 169, 0, 1, 41, 0, 1],[72, 172, 1, 3, 43, 0, 2],[69, 168, 0, 2, 42, 1, 2],[82, 179, 0, 3, 45, 0, 0],[77, 175, 1, 2, 44, 0, 2]])
print("Predicted Value:", prediction)

Predicted Value: [1 1 0 1 1]


In [169]:
actual = targets[80:86]
actual

array([0, 1, 0, 1, 1])

In [170]:
model_acc = metrics.accuracy_score(actual, prediction)
print("Accuracy =",model_acc*100)

Accuracy = 80.0


In [171]:
print('Recall:= %.3f' % recall_score(actual, prediction))

Recall:= 1.000


In [172]:
print('Precision:= %.3f' % precision_score(actual, prediction))

Precision:= 0.750
